include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - "build/**"
    - "**/*.schema.dart"
    - "**/*.g.dart"
linter:
  rules:
    file_names: false
    sort_pub_dependencies: false
    public_member_api_docs: false
